export default {
  QueryList: 'QueryList', //'查询',
  Add: 'Add', //'新建',
  Edit: 'Edit', //'修改',
  Delete: 'Delete', //'删除',
  Resetting: 'Resetting', //重置,
  DistributionRole: 'DistributionRole', //'分配角色',
  Frozen: 'Frozen', //'冻结解冻用户',
  EditPassword: 'EditPassword', //'修改密码',
  PermissionConfiguration: 'PermissionConfiguration', //'权限配置',
  BindUser: 'BindUser', //'绑定用户',
  DistributionDomain: 'DistributionDomain', //'分配域名',
  BindingCollector: 'BindingCollector', //'绑定采集器',
  SignIn: 'SignIn', //'登录',
  BindingMatch: 'BindingMatch', //'绑定赛事',
  Unbind: 'Unbind', //'取消绑定',
  UpdateForecastResults: 'UpdateForecastResults', //'更新预测结果',
  ChatRoomManage: 'ChatRoomManage', //'聊天室管理',
  ViewForecast: 'ViewForecast', //'查看预测',
  ViewIntelligence: 'ViewIntelligence', //'查看情报',
  ViewOdds: 'ViewOdds', //'查看赔率',
  PushAppointMessage: 'PushAppointMessage', //'推送指定用户',
  PushAllMessage: 'PushAllMessage', //'推送所有用户消息',
  PushMessage: 'PushMessage', //'推送消息',
  UndoPush: 'UndoPush', //'撤销推送',
  AuditDisplay: 'AuditDisplay', //'审核显示',
  RecommendedComments: 'RecommendedComments', //'推荐评论',
  Details: 'Details', //'详情',
  Reply: 'Reply', //'回复',
  FreezeUnfreezeUsers: 'FreezeUnfreezeUsers', //'冻结解冻用户',
  ResetPassword: 'ResetPassword', //'重置密码',
  IMManage: 'IMManage', //'IM管理',
  LandingAddMore: 'LandingAddMore', //'落地页添加更多',
  ViewScreenshot: 'ViewScreenshot', //'查看截图',
  AuditActivities: 'AuditActivities', //'审核活动',
  ImportMobile: 'ImportMobile', //'导入号码库',
  ExportMobile: 'ExportMobile', //'导出号码库',
  ResetCache: 'ResetCache', //'重置字典缓存',
  AddSubDepartment: 'AddSubDepartment', //添加子部门
  AddSubMenu: 'AddSubMenu', //添加子菜单
  Apply: 'Apply', //申请
  CancelApply: 'CancelApply', //撤销申请
  ProcessRecord: 'ProcessRecord', //流程记录
  NumberRecycling: 'NumberRecycling', //号码回收
  NumbeDetails: 'NumbeDetails', //号码明细
  ProxyGroup: 'ProxyGroup', //分组管理
};
